#############################################################################
# Makefile for building: darcoi
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  darcoi.pro
# Template: subdirs
# Command: /usr/local/qt5pi/bin/qmake -o Makefile darcoi.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/local/qt5pi/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-3rdparty-fftreal \
		sub-app


sub-3rdparty-fftreal-qmake_all:  FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile
	cd 3rdparty/fftreal/ && $(MAKE) -f Makefile qmake_all
sub-3rdparty-fftreal: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile
sub-3rdparty-fftreal-make_first-ordered: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-3rdparty-fftreal-make_first: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-3rdparty-fftreal-all-ordered: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-3rdparty-fftreal-all: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-3rdparty-fftreal-clean-ordered: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-3rdparty-fftreal-clean: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-3rdparty-fftreal-distclean-ordered: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-3rdparty-fftreal-distclean: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-3rdparty-fftreal-install_subtargets-ordered: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-3rdparty-fftreal-install_subtargets: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-3rdparty-fftreal-uninstall_subtargets-ordered: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-3rdparty-fftreal-uninstall_subtargets: FORCE
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-3rdparty-fftreal-qmake_all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile
	cd app/ && $(MAKE) -f Makefile qmake_all
sub-app: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile
sub-app-make_first-ordered: sub-3rdparty-fftreal-make_first-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-app-make_first: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-app-all-ordered: sub-3rdparty-fftreal-all-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-app-all: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-app-clean-ordered: sub-3rdparty-fftreal-clean-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-clean: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-distclean-ordered: sub-3rdparty-fftreal-distclean-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-distclean: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets-ordered: sub-3rdparty-fftreal-install_subtargets-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-app-install_subtargets: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets-ordered: sub-3rdparty-fftreal-uninstall_subtargets-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-uninstall_subtargets: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: darcoi.pro /usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/usr/local/qt5pi/mkspecs/common/shell-unix.conf \
		/usr/local/qt5pi/mkspecs/common/unix.conf \
		/usr/local/qt5pi/mkspecs/common/linux.conf \
		/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/usr/local/qt5pi/mkspecs/qdevice.pri \
		/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/qt5pi/mkspecs/qconfig.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		darcoi.pri \
		/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/usr/local/qt5pi/mkspecs/features/lex.prf \
		darcoi.pro
	$(QMAKE) -o Makefile darcoi.pro
/usr/local/qt5pi/mkspecs/features/spec_pre.prf:
/usr/local/qt5pi/mkspecs/common/shell-unix.conf:
/usr/local/qt5pi/mkspecs/common/unix.conf:
/usr/local/qt5pi/mkspecs/common/linux.conf:
/usr/local/qt5pi/mkspecs/common/gcc-base.conf:
/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt5pi/mkspecs/common/g++-base.conf:
/usr/local/qt5pi/mkspecs/common/g++-unix.conf:
/usr/local/qt5pi/mkspecs/qdevice.pri:
/usr/local/qt5pi/mkspecs/features/device_config.prf:
/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf:
/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf:
/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf:
/usr/local/qt5pi/mkspecs/qconfig.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_help.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_script.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt5pi/mkspecs/features/qt_functions.prf:
/usr/local/qt5pi/mkspecs/features/qt_config.prf:
/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/usr/local/qt5pi/mkspecs/features/spec_post.prf:
/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf:
/usr/local/qt5pi/mkspecs/features/default_pre.prf:
darcoi.pri:
/usr/local/qt5pi/mkspecs/features/resolve_config.prf:
/usr/local/qt5pi/mkspecs/features/default_post.prf:
/usr/local/qt5pi/mkspecs/features/warn_on.prf:
/usr/local/qt5pi/mkspecs/features/testcase_targets.prf:
/usr/local/qt5pi/mkspecs/features/exceptions.prf:
/usr/local/qt5pi/mkspecs/features/yacc.prf:
/usr/local/qt5pi/mkspecs/features/lex.prf:
darcoi.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile darcoi.pro

qmake_all: sub-3rdparty-fftreal-qmake_all sub-app-qmake_all FORCE

make_first: sub-3rdparty-fftreal-make_first-ordered sub-app-make_first-ordered FORCE
all: sub-3rdparty-fftreal-all-ordered sub-app-all-ordered FORCE
clean: sub-3rdparty-fftreal-clean-ordered sub-app-clean-ordered FORCE
distclean: sub-3rdparty-fftreal-distclean-ordered sub-app-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-3rdparty-fftreal-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-3rdparty-fftreal-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

sub-3rdparty-fftreal-check_ordered:
	@test -d 3rdparty/fftreal/ || mkdir -p 3rdparty/fftreal/
	cd 3rdparty/fftreal/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/3rdparty/fftreal/fftreal.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-app-check_ordered: sub-3rdparty-fftreal-check_ordered 
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/jimtendo/darcoiv3/app/app.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-3rdparty-fftreal-check_ordered sub-app-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

